name: nubia-sm8350-kernel
adopt-info: kernel

parts:
  kernel:
    plugin: kernel
    source: https://github.com/piashmsubd/android_kernel_nubia_sm8350.git
    source-type: git
    kernel-image-target: Image.gz
    kernel-compiler: gcc
    kernel-compiler-version: "10"
    kernel-initrd-modules:
      - ext4
      - vfat
    kernel-device-trees:
      - nubia-sm8350
    build-packages:
      - bc
      - build-essential
      - libssl-dev
      - flex
      - bison
    override-build: |
      make defconfig
      make -j$(nproc)
      snapcraftctl set-version $(make kernelversion)

  firmware:
    plugin: dump
    source: firmware/
    organize:
      '*': lib/firmware/

slots:
  kernel-module-control:
  hardware-observe:
  system-observe:
  system-trace:

