name: Build TWRP Recovery

on:
  push:
    branches:
      - Twrp_12.1
  pull_request:
    branches:
      - Twrp_12.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 python3-pip

    - name: Set up repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Initialize repo
      run: |
        repo init -u https://github.com/piashmsubd/TWRP_NX669J_12.1.git -b Twrp_12.1

    - name: Sync repo
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        lunch twrp_NX669J-eng
        mka recoveryimage
